name: web_admin
description: Interface Web d’administration OctoDecks
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^2.0.10+1
  http: ^1.2.1

  # 🔌 Dépendance locale vers le code partagé
  core:
    path: ../../core

  # (Optionnel) Pour développement web uniquement
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
  - assets/icons/banner/banner_octodecks_1.png