name: Build weekly prices

on:
  schedule:
    - cron: '0 3 * * 0'   # dimanche 03:00 UTC
  workflow_dispatch:       # exécution manuelle possible

jobs:
  weekly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # --- install Python deps si besoin ---
    - run: pip install --quiet firebase-admin google-cloud-storage

    # --- Télécharger la base la + récente depuis le bucket ---
    - name: Download current DB
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_BUCKET:          ${{ secrets.FIREBASE_BUCKET }}
      run: |
        python - <<'PY'
        import json, os, firebase_admin
        from google.cloud import storage, exceptions

        cred = firebase_admin.credentials.Certificate(
            json.loads(os.environ['FIREBASE_SERVICE_ACCOUNT']))
        firebase_admin.initialize_app(cred, {
            'storageBucket': os.environ['FIREBASE_BUCKET']
        })

        bucket = storage.bucket()
        blob   = bucket.blob("octobase/octobase_reference.db")
        blob.download_to_filename("database/octobase_reference.db")
        print("DB téléchargée")
        PY

    # --- Recalcul hebdo ---
    - name: Build weekly price tables
      run: python tools/build_weekly_prices.py

    # --- Re-upload de la base ---
    - name: Upload DB back
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_BUCKET:          ${{ secrets.FIREBASE_BUCKET }}
      run: |
        python - <<'PY'
        import json, os, firebase_admin
        from firebase_admin import storage as fb_storage

        cred = firebase_admin.credentials.Certificate(
            json.loads(os.environ['FIREBASE_SERVICE_ACCOUNT']))
        firebase_admin.initialize_app(cred, {
            'storageBucket': os.environ['FIREBASE_BUCKET']
        })

        bucket = fb_storage.bucket()  
        blob   = bucket.blob("octobase/octobase_reference.db")
        blob.upload_from_filename("database/octobase_reference.db",
                                  content_type="application/octet-stream")
        print("✅ Upload weekly DB terminé")
        PY
